name: eqcorrscan-test
channels:
  - conda-forge
dependencies:
  # Compiler bits to match conda-forge build env
  - cctools_osx-64
  - clang=14
  - clang-14
  - clang_osx-64
  - llvm-openmp
  - clangxx=14
  - compiler-rt
  - compiler-rt_osx-64
  - ld64_osx-64
  - libclang-cpp14
  - libcxx=14
  - libllvm14
  - llvm-tools  
  # Normal requirements
  - numpy>=1.12
  - matplotlib>=1.3.0
  - scipy
  - mock
  - obspy>=1.4.0
  - h5py>3.3  # Issue with dep resolution: https://github.com/conda-forge/h5py-feedstock/issues/92
  - pyyaml
  - bottleneck
  - fftw
  - pytest>=2.0.0
  - pytest-cov
  - pytest-pep8
  - pytest-xdist
  - pytest-rerunfailures
  - pytest-mpl<0.16.0
  - codecov
  - boto3
