name: eqcorrscan-test
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - matplotlib
  - scipy
  - mock
  - obspy
  - h5py
  - pyyaml
  - bottleneck
  - fftw
  - pytest
  - pytest-cov
  - pytest-pep8
  - pytest-xdist
  - pytest-rerunfailures
  - pytest-mpl
  - codecov
  - pip
  - pip:
    - pyfftw
