name: eqcorrscan-test
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::compilers
  - numpy>=1.12
  - matplotlib>=1.3.0
  - scipy
  - mock
  - obspy>=1.4.0
  - h5py
  - pyyaml
  - bottleneck
  - fftw
  - pytest>=2.0.0
  - pytest-cov
  - pytest-pep8
  - pytest-xdist
  - pytest-rerunfailures
  - pytest-mpl
  - codecov
  - boto3
  - sqlite>=3.49.2
  - libsqlite>=3.49.2  # Pinning temporarily to cope with mismatched version errors
