name: eqcorrscan-test
channels:
  - conda-forge
  - defaults
dependencies:
  - clangdev>=4
  - openmp>=4
  - libcxx>=4
  - cctools
  - clang
  - clang_osx-64
  - compiler-rt
  - libcxx
  - llvm-openmp>=4.0.1
  - numpy>=1.12
  - matplotlib>=1.3.0
  - scipy>=0.18,<1.9.0  # Pinned due to scipy/obspy hanning renaming
  - mock
  - obspy>=1.4.0
  - h5py<3.2  # Issue with dep resolution: https://github.com/conda-forge/h5py-feedstock/issues/92
  - pyyaml
  - bottleneck
  - fftw
  - pytest>=2.0.0
  - pytest-cov
  - pytest-pep8
  - pytest-xdist
  - pytest-rerunfailures
  - pytest-mpl<0.16.0
  - codecov
  - pip
  - pip:
    - pyfftw
