name: eqcorrscan-test
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy>=1.12
  - matplotlib>=1.3.0
  - scipy>=0.18
  - mock
  - obspy>=1.3.0
  - h5py
  - pyyaml
  - bottleneck
  - fftw
  - pytest>=2.0.0
  - pytest-cov
  - pytest-pep8
  - pytest-xdist
  - pytest-rerunfailures
  - pytest-mpl
  - codecov
  - pip
  - pip:
    - pyfftw
