

# AppVeyor.com is a Continuous Integration service to build and run tests under Windows

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: https://stackoverflow.com/a/13751649
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\misc\\appveyor\\run_with_env.cmd"
    PYTHON: "C:\\conda"
    MINICONDA_VERSION: "3.7.0"
    CI_URL: "--ci-url https://ci.appveyor.com/project/%APPVEYOR_REPO_NAME%/build/1.0.%APPVEYOR_BUILD_NUMBER%-%APPVEYOR_REPO_BRANCH%"
    PR_URL: "--pr-url https://github.com/%APPVEYOR_REPO_NAME%/pull/%APPVEYOR_PULL_REQUEST_NUMBER%"

  matrix:
    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Miniconda35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      SKIP_NOTAG: "true"

    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      SKIP_NOTAG: "true"

matrix:
    allow_failures:
      - PYTHON_VERSION: "3.5"
    fast_finish: true

install:
  - '.\\misc\\appveyor\\trim_path.bat'
  - "ECHO %PATH%"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # Check that we have the expected version and architecture for Python
  - "%CMD_IN_ENV% python --version"
  # Install fftw
  - "choco install curl"
  - "choco install 7z"
  - "%CMD_IN_ENV% ./misc/appveyor/setup_fftw_dlls.cmd"
  # Install the build and runtime dependencies of the project.
  - "conda update -q --yes conda"
  - "conda config --add channels conda-forge"
  # Create a conda environment using the astropy bonus packages
  - "conda create -q --yes -n test python=%PYTHON_VERSION%"
  - "activate test"
  # Install default dependencies
  - "conda install -q --yes pip numpy>=1.12.0 scipy>=0.18 matplotlib mock flake8 pyflakes=0.9.0 cython h5py"
  # additional dependecies
  - "pip install pyimgur"

    # Obspy 1.0.3 conda clashes with numpy >= 1.12...(because of matplotlib 1.5.*?) install via git until 1.1.0
  - "mkdir obspy && cd obspy && git init"
  - "git remote add -f origin https://github.com/obspy/obspy.git"
  - "git pull origin master"
  - "python setup.py install"
  - "cd .."
  - "rm -rf obspy"

  # Install other pip dependancies
  - "pip install -U future"
  - "pip install pytest pytest-pep8 pytest-cov pytest-xdist codecov"
  # list package versions
  - "conda list"

# Not a .NET project
build: false

test_script:
  - "%CMD_IN_ENV% python setup.py develop"
  - "%CMD_IN_ENV% py.test --ignore=eqcorrscan/tests/tutorial_test.py"

after_test:
  #  - "coverage combine"
  - "powershell copy-item .coverage ..\\.coverage.empty"
  - "cd .."
  - "coverage combine"
  - "codecov"
