# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
general:
  branches:
    ignore:
      - gh-pages

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.5

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install numpy>=1.12
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: install fftw
          command: |
            sudo apt-get update
            sudo apt-get install libfftw3-dev
      - run:
          name: install EQcorrscan
          command: |
            . venv/bin/activate
            python setup.py install
            python setup.py build_ext --inplace
      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            py.test -m "network" -n 2
            py.test eqcorrscan/doc/tutorials/*.rst eqcorrscan/doc/submodules/*.rst --cov-append

      - run:
          name: Upload to codecov
          command: |
            . venv/bin/activate
            ls -a
            codecov

      - store_artifacts:
          path: test-reports
          destination: test-reports
